### ISSUE TITLE
Cannot execute any function in the editor

### ISSUE THREAD

**Issue by rodionnv** [kbss-cvut/s-pipes-editor-ui#24]
![image](https://github.com/kbss-cvut/s-pipes-editor-ui/assets/130922166/cb9ff497-5fa7-46b4-9f48-eef883dc3180)
When I try to execute any function with the editor I get "ERROR during script execution", in the LOG message invalid/no module id supplied

**Comment by blcham** [comment]
@rodionnv After https://github.com/kbss-cvut/s-pipes-editor-ui/pull/22 is merged you can use variable `SPIPES_ENGINE` to configure your own s-pipes engine.

**Comment by blcham** [comment]
FYI, @kostobog

**Comment by kostobog** [comment]
@blcham @rodionnv 
I managed to execute function `http://onto.fel.cvut.cz/ontologies/s-pipes/hello-world-example-0.1/execute-greeting` from script `s-pipes/doc/examples/hello-world/hello-world.sms.ttl` and to view the execution log. There were two issues:
* the request parameters of requests to s-pipes service were wrong see kbss-cvut/s-pipes-editor#27
* there was an issue in s-pipes kbss-cvut/s-pipes#193 which is solved here kbss-cvut/s-pipes#194
