### ISSUE TITLE
Some sm:next arrows are not visualized

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor-ui#25]
See which arrows are missing:
![image](https://github.com/kbss-cvut/s-pipes-editor-ui/assets/3962237/8d220312-aff7-4e95-a7b7-ea84a07496df)

Here is relevant script where it occurs:
[statistics-extraction.sms.ttl.gz](https://github.com/kbss-cvut/s-pipes-editor-ui/files/12255201/statistics-extraction.sms.ttl.gz)

```[tasklist]
### Tasks
- [ ] https://github.com/kbss-cvut/s-pipes-editor/issues/25
```

**Comment by blcham** [comment]
@rodionnv please investigate the issue and let me know if you get stuck

**Comment by blcham** [comment]
@rodionnv 
I believe `cd s-pipes-modules; git pull` would solve the issue.

**Comment by blcham** [comment]
Ok, then I don't know then ... I just hope you **did** `cd s-pipes/../s-pipes-modules` instead of  `cd s-pipes/s-pipes-modules`.

**Comment by kostobog** [comment]
The issue with the missing modules should be resolved by adding an import statement 
`owl:imports <http://onto.fel.cvut.cz/ontologies/lib/sm-module-adapter> ;`
in the ontology `s-pipes-modules/s-pipes.ttl`. 

@blcham not sure if we should pushed to `s-pipes-modules`

**Comment by kostobog** [comment]
Task https://github.com/kbss-cvut/s-pipes-editor/issues/25 is resolved in https://github.com/kbss-cvut/s-pipes-editor/pull/26

**Comment by blcham** [comment]
@kostobog we should not need `sm-module-adapter` ontology. The ontology is useful only to show the pipeline in topbraid composer, which we will not use soon anymore.

What axiom from sm-module-adapter ontology you need?

**Comment by blcham** [comment]
`sml:BindWithConstant rdfs:subClassOf sm:Modules .`

**Comment by blcham** [comment]
@blcham need to refactor `sm-module-adapter ontology` to finish this issue.

**Comment by blcham** [comment]
I finished refactoring of RDF ontologies in s-pipes-modules and now it works correctly.
![image](https://github.com/kbss-cvut/s-pipes-editor-ui/assets/3962237/d84dc183-8a2e-49b4-9179-940277628310)

@rodionnv make sure that it works for you and close this ticket.

**Comment by rodionnv** [comment]
@blcham Yes, it works for me.
