### ISSUE TITLE
Update to react 18

### ISSUE THREAD

**Issue by palagdan** [kbss-cvut/s-pipes-editor-ui#49]
- [x] Update s-pipes-editor-ui to react 18
     - [x]  Update all libraries that depend on React, and remove any that do not support React 18.
     - [x] Find alternative libraries for any that are removed, and replace them in the application.

**Comment by palagdan** [comment]
I tried to upgrade react to version 18 and got the error 
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from @hot-loader/react-dom@17.0.2
npm ERR! node_modules/@hot-loader/react-dom
npm ERR!   dev @hot-loader/react-dom@"^17.0.2" from the root project
```
So I decided to remove package  @hot-loader/react-dom because last update was 3 years ago and it does not support react 18. This dependency was for:
```
Hot Module Replacement (HMR): It updates modules in a running application without a full page reload. 
This is especially useful for React components, 
as it allows developers to see changes instantly without losing the state of the application.
```

Then I remove "react-delay-render" because it was updated 7 years ago and there is almost no downloads on npm website.
Then I remove  "react-hot-loader" because it isnt update for 2 years.
Them I remove react react-loadingg because last update was 4 years ago

**Comment by blcham** [comment]
@palagdan so I am not sure, what you mean by "I decided to remove" and "then I remove" ...

So you are in the middle of doing this ticket or you wanted to close it this way and leave for later? If you did some work, why not creating PR instead?

**Comment by palagdan** [comment]
@blcham I just left some notes for myself here to track how I was solving this problem and forgot to delete them. Yes, this ticket is in progress.
